### ISSUE TITLE
GADBannerViewDelegate.h not found - first issue

### ISSUE THREAD

**Issue by YBthebest** [larsacus/LARSAdController#111]
Hi,

first of all thanks a lot for this great little tool.
I followed the complete installation process through cocoapods and it all seemed to work perfectly. But when I tried to first build the project, I got the above error in the TOLAdAdapterGoogleAds.h file.  I then copied the whole AdMob SDK in the Core folder of the LarsAdController folder, and it worked.

But now, following your tutorial, I tried to Register the ad networks by adding the two following lines in my AppDelegate:
    [[LARSAdController sharedManager] registerAdClass:[TOLAdAdapteriAds class]];
    [[LARSAdController sharedManager] registerAdClass:[TOLAdAdapterGoogleAds class] withPublisherId:publisherId];

Immediately, I got some undeclared identifier errors for LARSAdController. I tried adding the following lines at the top:
#import "Pods/LARSAdController/Source/LARSAdController.h"
#import "Pods/LARSAdController/Source/TOLAdAdapteriAds.h"
#import "Pods/LARSAdController/Source/TOLAdAdapterGoogleAds.h"
And it seemed to work, except now it's again giving me an error for the publisherId...

I don't get it, error after error. I must've missed something, but what?

Thanks a lot

**Comment by larsacus** [comment]
CocoaPods should configure everything for you. If this didn't work, then something didn't work correctly with `pod install`.

You should only have to import `#import <LARSAdController/LARSAdController.h>` to your project.

**Comment by YBthebest** [comment]
When I import the line you said in AppDelegate, I still get the Use of undeclared identifier 'TOLAdAdapteriAd' and GoogleAds...
Any way to simply reverse the pod install and redo it?

If I keep the imports I had before and try to display an ad, I get:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LARSAdController", referenced from:
      objc-class-ref in FirstViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by larsacus** [comment]
what does your entry for LARSAdController in your podfile look like?

**Comment by YBthebest** [comment]
platform :ios, '6.0'

pod 'LARSAdController', '~> 3.0'

xcodeproj 'path to my xcode proj (the correct path)'

I had to change the 5.0 to 6.0 because otherwise pod install didn't work. I had to add the last line too because apparently it couldn't locate my xcodeproj easily otherwise...

**Comment by larsacus** [comment]
Everything should work properly, I'm not sure what the problem is.

**Comment by YBthebest** [comment]
Ah, it annoys me so much... is there any way to "clean" uninstall the Pods? To go back to my project before the pod install? Thanks a lot Lars.

**Comment by YBthebest** [comment]
http://stackoverflow.com/questions/22198000/is-it-feasible-to-ditch-cocoapods-after-issuing-pod-install-in-ios-app I managed to do it thanks to this.
