### ISSUE TITLE
Notification on bannerViewActionShouldBegin and bannerViewActionDidFinish

### ISSUE THREAD

**Issue by Djelibeybi** [larsacus/LARSAdController#113]
I can't seem to find a way to get notified via the LARSAdController for the standard iAd delegate methods, in particular bannerViewActionShouldBegin and bannerViewActionDidFinish.

I need to stop some activity before the ad is displayed modally and then resume the activity once the ad has completed, assuming the user returns to the app. Is there an existing mechanism to do this?

**Comment by larsacus** [comment]
I currently don't have support for this kind of callback since I don't have support for delegation on the ad controller itself - only callbacks for the controller's ad visibility. I did this in an effort to make this library serve the 80% use-case in as few lines of setup code as possible.

**Comment by Djelibeybi** [comment]
Ok, I've worked around this by modifying my local version of LARSAdController. Can I ask that this be added as a feature request for consideration?

**Comment by larsacus** [comment]
I'm always open to pull requests.
