### ISSUE TITLE
error "Include of non-modular header inside framework module "

### ISSUE THREAD

**Issue by nahung89** [larsacus/LARSAdController#118]
here is my srcreenshot: http://imgur.com/NcVsQNN

In pod file, I add

platform :ios, '6.0'
target 'abc' do
inhibit_all_warnings!
pod 'LARSAdController', '3.0'
end

**Comment by nahung89** [comment]
here is my srcreenshot: http://imgur.com/NcVsQNN 

In pod file, I add

platform :ios, '6.0'
target 'abc' do
inhibit_all_warnings!
pod 'LARSAdController', '3.0'
end

**Comment by larsacus** [comment]
You are explicitly specifying an old version of this pod. please use the latest version of the pod

```pod 'LARSAdController', '3.1.0'```

or use a more flexible version specification: 

```pod 'LARSAdController', '~> 3.0'```

**Comment by MarcoMoby** [comment]
How can I verify the version? because on El Capitan I am getting some warnings while updating pods, it says I am using 3.1 (my pod entry look like this: pod 'LARSAdController', '~> 3.0') but it gives me the same errors and it does no longer compile the project.

**Comment by larsacus** [comment]
It sounds like you need to update cocoapods. The error you described isn't related to my source specifically, but how the source is built.

**Comment by MarcoMoby** [comment]
I understand, but afaik cocoapods is up to date:
`$ pod --version`
`0.38.2`

Also, it does not seem to happen with any other pod.

**Comment by larsacus** [comment]
I've been having a lot of problems with the CocoaPods + GoogleMobileAds pod since google switched to using a fake framework without source. I will look into this, but I might just have to remove pod support for google ads since nothing is working consistently over time.
