### ISSUE TITLE
Portrait ads do not display correctly on iPad Pro 12.9"

### ISSUE THREAD

**Issue by dafdafydd** [larsacus/LARSAdController#131]
Hello,

I am currently updating one of my apps and noticed that ads do not display correctly on iPad Pro 12.9" - the ad is bigger than the screen size. When changed to landscape, everything works fine. I am attaching an image that shows what is happening.

Do you have an idea what could be responsible for that and how to fix it?

![img_0806](https://cloud.githubusercontent.com/assets/5732680/17983598/c06f42dc-6b0d-11e6-8e32-bbac635befc0.PNG)

**Comment by larsacus** [comment]
Due to the iAd network shutdown, I would recommend simply using Google ad mediation directly, instead. This class has limited to no usefulness without iAd, unfortunately.

https://developer.apple.com/support/iad/
